site_name: Völur AI SDK documentation
repo_url: https://github.com/volur-ai/python-volur-ai-sdk
theme:
  name: material
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
            - gen
nav:
  - Code Reference: reference/
  - 'index.md'
