site_name: Völur SDK documentation
repo_url: https://github.com/volur-ai/python-volur-sdk
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_pages.py # https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
            - gen
          import:
            - https://googleapis.dev/python/google-api-core/latest/objects.inv
# Please keep the following list of extensions in alphabetical order
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: 'index.md'
  - Installation: installation.md
  - Authentication: authentication.md
  - Getting Started: getting-started.md
  - Data Model: 'data-model.md'
  - Deploying: 'deploying.md'
  - API Reference: reference/
  - Examples: examples/


watch:
  - src/
  - gen/
  - scripts/
