name: Publish documentation
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-docs-${{ github.ref }}
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1
        with:
          version: ">=0.8 <1.0"
      - uses: azure/login@v2
        with:
          client-id: 72305ec0-00fa-4764-8d6e-db889cf0dfeb
          tenant-id: db8e8782-f851-479a-8db9-5b97c9edcdb4
          subscription-id: 9388d108-4782-45ba-b99e-ced5570f1d3a
      - uses: actions/setup-go@v5
      - run: |
          earthly +build-docs
          go install github.com/rclone/rclone@latest
          rclone sync site :azureblob,env_auth:\$web
        env:
          AZURE_STORAGE_ACCOUNT_NAME: voluraisdkpythondocs
